language: java

jdk:
  - openjdk-ea
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

jobs:
  allow_failures:
    # Fail maven-bundle-plugin on JDK 15 (https://issues.apache.org/jira/browse/FELIX-6259,https://github.com/mybatis/parent/issues/160)
    - jdk: openjdk-ea

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    - secure: "dgaO+01IuaJgtHpZ2z3leAfU91vgfRtjJpCuGdhvoSs03uU7kuQGXmm8Fg8b\n8Z8DqBCO+mJY47WNrwlBrb2Xbo12YRxZViG9tEnhvaWogNKJ62wLBIOC/wvD\nLeQZeAcgXQvbA2Ug8Lg0NXxqtI5depdMOHzA2QSApLl2izW97Wc="
    - secure: "OowVY4Gao6pTRQFgHHLVx8gEtBeAOH6A7jLubFDzBizLGFFEHvEfV+PckM9C\nHRXpxCjGyWxBu0O9yClda0BXXQhNTGgAvso8A/XvZxr06dHIZy//QoR3U6GS\nzdVPaERRPSJEzDUEHdquhpWLiJd/tQaky9gK70HabjDf7+FcOoo="
